language: node_js

addons:
  chrome: stable
  
node_js:
  - 10
  - 12

before_install:
  - npm install -g gulp
  - npm install -g typescript
  - npm install -g rollup
  - npm install

script:
  - gulp build
