language: node_js

addons:
  chrome: stable
  
node_js:
  - 8
  - 9
  - 10

before_install:
  - npm install -g gulp
  - npm install -g typescript
  - npm install -g rollup
  - npm install

script:
  - gulp ci
